### ISSUE TITLE
Documentation on constrained generation?

### ISSUE THREAD

**Issue by lumost** [floneum/floneum#107]
**Problem**

Hello! I'm interested in using KALOSM's constrained generation in a project of mine, but I can only observe a single example which instantiates an opaquely defined parser. Is there a brief doc on the capabilities of constrained generation available? 

Thanks for the solid work on this project!

**Comment by ealmloff** [comment]
👋, Each parser needs to be able to take the state of the parser, and an input and return either the completed value, incomplete with a new parser state that can be resumed later or an error. Structured generation just creates text that can be parsed by some parser. Eventually I would like to create a book for Kalosm with examples and explanations of different APIs, but until then here are some examples:

Here is an example that shows how you can define a parser: https://github.com/floneum/floneum/blob/master/interfaces/kalosm/examples/chat-with-character.rs#L38-L83 (There are also a bunch of other implementations here https://github.com/floneum/floneum/tree/master/interfaces/kalosm-sample/src/structured_parser)
Here is an example of parsing rust types: https://github.com/floneum/floneum/blob/master/interfaces/kalosm/examples/constrained-rust-types.rs#L11
Or here is an example of combining multiple parsers: https://github.com/floneum/floneum/blob/master/interfaces/kalosm/examples/constrained.rs#L74-L77

**Comment by ealmloff** [comment]
There is also now a chapter in the docs book about constrained generation: https://floneum.com/kalosm/docs/reference/llms/structured_generation
