### ISSUE TITLE
Stream incompatibility with ecosystem?

### ISSUE THREAD

**Issue by jondot** [floneum/floneum#114]
Hi, I'm trying to use kalosm on an Axum router, and to stream the text generation.
Looks like something in `ChannelTextStream` just won't fit the general concept of how Axum expect a regular `Stream` (or tokio?)

This expects a `TryStream`:

```rust
async fn candle_llm() -> impl IntoResponse {
    println!("building model");
    let mut model = Llama::builder()
        .with_source(LlamaSource::llama_7b_code())
        .build()
        .unwrap();
    println!("building model: done");
    let prompt = "write binary search";
    println!("{prompt}");
    let mut result = model.stream_text(prompt).await.unwrap();
    println!("stream ready");
    Body::from_stream(result.into()) // compilation error
}
```

Here's an example trying to use SSE, which hangs (no streaming):

```rust
struct Streamer {
    inner: ChannelTextStream<String>,
}
impl Stream for Streamer {
    type Item = Result<Event, Infallible>;

    fn poll_next(
        mut self: std::pin::Pin<&mut Self>,
        cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<Option<Self::Item>> {
        self.inner
            .poll_next_unpin(cx)
            .map(|s| Some(Ok(Event::default().data(s.unwrap_or_default()))))
    }
}

async fn candle_llm() -> Sse<impl Stream<Item = Result<Event, Infallible>>> {
    println!("building model");
    let mut model = Llama::builder()
        .with_source(LlamaSource::llama_7b_code())
        .build()
        .unwrap();
    println!("building model: done");
    let prompt = "write binary search";
    println!("{prompt}");
    let mut result = model.stream_text(prompt).await.unwrap();
    println!("stream ready");
    Sse::new(Streamer { inner: result }).keep_alive(
        axum::response::sse::KeepAlive::new()
            .interval(Duration::from_secs(1))
            .text("keep-alive-text"),
    )
}
```

**Comment by ealmloff** [comment]
Axum and Kalosm use the same stream type (from futures-rs). You just need to map the stream to map the stream into a stream of results like this:

```
fn infallible(t: String) -> Result<String, std::convert::Infallible> {
    println!("added {t} to stream");
    Ok(t)
}
async fn candle_llm() -> impl IntoResponse {
    println!("building model");
    let mut model = Llama::builder()
        .with_source(LlamaSource::llama_7b_code())
        .build()
        .unwrap();
    println!("building model: done");
    let prompt = "write binary search";
    println!("{prompt}");
    let mut result = model.stream_text(prompt).await.unwrap();
    println!("stream ready");
    Body::from_stream(result.map(infallible).into()) // Adding infallible makes the stream return Result<T, E>
}
```

I have seen several people using candle to create a server. Here is a full example using axum and Kalosm to create a streaming server:
https://github.com/floneum/floneum/blob/master/interfaces/kalosm/examples/axum.rs

**Comment by jondot** [comment]
Thanks! that's a really great example!
I tried the solution, but still looks like Rust cannot understand ChannelTextStream (the `into` is failing asking for type hints). Anything i missed?

**Comment by jondot** [comment]
By some form of magic, removing `into()` worked, but I'm still not getting actual streaming tokens. Not from `print`s nor through `curl` (I also disable buffering in curl)

**Comment by jondot** [comment]
Looks like it was some kind of internal timeout -- all working now!

**Comment by jondot** [comment]
@ealmloff I have a couple of last questions

1. It seems the model is mut, and needs an RwLock. Using the examples -- additional requests use the same mut model, which is mutated upon each new request. Do we care about that?
2. I'm experiencing around 3-5x slower performance with kalosm using candle, against using the equivalent candle example (from the `quantized` folder). I've used the `metal` feature to enable `accelerate`, but not sure where else are the perf costs. Any idea where to start looking?

**Comment by ealmloff** [comment]
> @ealmloff I have a couple of last questions
> 
> 1. It seems the model is mut, and needs an RwLock. Using the examples -- additional requests use the same mut model, which is mutated upon each new request. Do we care about that?

That is just left over from the orignal sync models with the cache built into the model. https://github.com/floneum/floneum/pull/115 removes that

> 2. I'm experiencing around 3-5x slower performance with kalosm using candle, against using the equivalent candle example (from the `quantized` folder). I've used the `metal` feature to enable `accelerate`, but not sure where else are the perf costs. Any idea where to start looking?

One difference could be running it within the candle folder. Candle has some configuration set that makes the code run significantly faster. You can copy this configuration to enable those optimizations: https://github.com/floneum/floneum/blob/master/.cargo/config.toml and https://github.com/floneum/floneum/blob/master/Cargo.toml#L109-L111

**Comment by ealmloff** [comment]
@jondot Kalosm is also now [published on crates.io](https://crates.io/crates/kalosm)
