### ISSUE TITLE
Loading language models from local files

### ISSUE THREAD

**Issue by hugohmn** [floneum/floneum#145]
Thanks for the great work.
I think the support to load models (tokenizers and weights - whether gguf wor not) would be a great feature to implement.
Something like this :

```rust
let model = Llama::builder()
        .with_source(LlamaSource::tiny_llama_1_1b_chat()
        .with_model_file("path/to/local/gguf_file".to_string()))
        .build()
        .unwrap();
```

Thank you

**Comment by mariuszmalek** [comment]
It doesn't work. Is there any way to load the local model without downloading?

**Comment by ealmloff** [comment]
> It doesn't work. Is there any way to load the local model without downloading?

You can use the [Local](https://docs.rs/kalosm/latest/kalosm/language/enum.FileSource.html#variant.Local) variant of FileSource with a [custom Llamasource](https://github.com/floneum/floneum/blob/20568cf7d959035394b551af770ef8771dae7903/interfaces/kalosm/examples/custom_llama_source.rs#L9)

**Comment by mariuszmalek** [comment]
Thanks. I tried to do that but received an error:

error[E0618]: expected function, found `kalosm::language::Llama`
  --> src/main.rs:18:5
   |
6  |     let llm = Llama::builder()
   |         --- `llm` has type `kalosm::language::Llama`
...
18 |     llm(prompt).to_std_out().await.unwrap();
   |     ^^^--------
   |     |
   |     call expression requires function






My code:

#[tokio::main]
async fn main() {
    let llm = Llama::builder()
        .with_source(LlamaSource::new(
            FileSource::Local("models/SmolLM-135M.Q4_K_M.gguf".into()),
            FileSource::Local("models/SmolLM-135M.tokenizer.gguf".into()),
        ))
        .build()
        .await
        .unwrap();

    let prompt = "The following is a 300 word essay about why the capital of France is Paris:";
    print!("{}", prompt);

    llm(prompt).to_std_out().await.unwrap();
}

**Comment by ealmloff** [comment]
That example is updated for the git version of kalosm. The 0.3 examples are available here: https://github.com/floneum/floneum/tree/kalosm-0.3/interfaces/kalosm/examples

There isn't an exact equivalent of that example, but the API of `LlamaSource::new` is pretty similar in `0.3` except you need to set the tokenizer and chat markers manually like this gist: https://gist.github.com/ealmloff/3398d172180fa783f043b4a26960b19a

**Comment by mariuszmalek** [comment]
Thanks, but I still can't use this: no method named `unwrap` found for opaque type `impl Future<Output = Result<kalosm::language::Llama, kalosm::language::anyhow::Error>>` in the current scope
method not found in `impl Future<Output = Result<Llama, Error>>`rustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view:/diagnostic%20message%20[0]?0#file:///Users/mariusz/Desktop/aura/src/main.rs)
main.rs(27, 72): consider `await`ing on the `Future` and calling the method on its `Output`: `await.`

**Comment by mariuszmalek** [comment]
Thanks. I updated my code: `#[tokio::main]
async fn main() {

    let prompt = "The following is a 300 word essay about why the capital of France is Paris:";
    print!("{}", prompt);

    let local_source = LlamaSource::new(
        FileSource::Local("src/models/SmolLM-135M.Q4_K_M.gguf".into()),
        FileSource::Local("src/models/tokenizer.json".into()),
    )
    .with_group_query_attention(
        // 1 for llama, 8 for mistral
        8,
    )
    // If this is a chat model, you can set the chat markers it uses here
    .with_chat_markers(ChatMarkers {
        system_prompt_marker: "<s>[INST] ",
        end_system_prompt_marker: " [/INST]",
        user_marker: "[INST] ",
        end_user_marker: " [/INST]",
        assistant_marker: "",
        end_assistant_marker: "</s>",
    });

    // You can set the source of the model with the `with_source` method
    let model: Llama = Llama::builder().with_source(local_source).build().await.unwrap();

    let mut chat = Chat::builder(model).with_system_prompt("The assistant will act like a pirate").build();

    loop {
        chat.add_message(prompt);
    }

}` But I don't get any response :/

**Comment by ealmloff** [comment]
>         chat.add_message(prompt);

You need to use the object returned from add_message. See the original gist which uses `to_std_out`

**Comment by mariuszmalek** [comment]
> > ```
> >     chat.add_message(prompt);
> > ```
> 
> You need to use the object returned from add_message. See the original gist which uses `to_std_out`

When I use the same code as in gist, this error appears: error[E0277]: `ChannelTextStream` is not a future
  --> src/main.rs:37:14
   |
37 |             .await
   |             -^^^^^
   |             ||
   |             |`ChannelTextStream` is not a future
   |             help: remove the `.await`
   |
   = help: the trait `Future` is not implemented for `ChannelTextStream`
   = note: ChannelTextStream must be a future or must implement `IntoFuture` to be awaited
   = note: required for `ChannelTextStream` to implement `IntoFuture`

For more information about this error, try `rustc --explain E0277`.
