### ISSUE TITLE
CreateModel.start should return Result

### ISSUE THREAD

**Issue by prabirshrestha** [floneum/floneum#154]
The following trait should return `Result<Self>`. 

```rust
   pub trait CreateModel {
    /// Start the model.
    async fn start() -> Self;
}
```

Yesterday hugging face was down for serval hours and this was crashing as I didn't have the model downloaded. Returning a `Result` will allow the callers to handle failure cases.

https://twitter.com/huggingface/status/1762954032312639702

**Comment by ealmloff** [comment]
That API should return a result. Additionally, there should be an option to pass in a callback that will be called while the model download progresses
