### ISSUE TITLE
Integrate other model types

### ISSUE THREAD

**Issue by ealmloff** [floneum/floneum#16]
Floneum should allow you to interact with other model types like image generation models (stable diffusion) and specialized embedding models (Clip).

The main difficulty here will be running other model types that do not require any external dependancies.

Here are a few libraries that look promising:
- https://github.com/monatis/clip.cpp
- https://github.com/saharNooby/rwkv.cpp
- https://github.com/ggerganov/whisper.cpp
- https://github.com/skeskinen/bert.cpp

**Comment by Demonthos** [comment]
https://github.com/Gadersd/whisper-burn also looks promising without requiring a new binding library

**Comment by ealmloff** [comment]
Integrating some of the examples from [candle](https://github.com/huggingface/candle) seems much easier here than creating new bindings to c libraries. It looks like candle will support [quantization](https://github.com/huggingface/candle/issues/359) in the future which should make these models almost as fast as the raw ggml versions
