### ISSUE TITLE
Failed to compile 'floneum-cli v0.1.0'

### ISSUE THREAD

**Issue by jtommi** [floneum/floneum#162]
**Problem**

I'm following the steps described in ["Your first plugin"](https://floneum.com/docs/developer/first_plugin#your-first-plugin)
But when doing `cargo install --git https://github.com/floneum/floneum floneum-cli`, I get `Failed to compile 'floneum-cli v0.1.0'`

> Caused by:
>   failed to select a version for `wasmtime-wasi`.
>       ... required by package `floneum_plugin v0.1.0 (C:\Users\xxx\.cargo\git\checkouts\floneum-61df347afec392d9\c314e5d\plugin)`
>       ... which satisfies path dependency `floneum_plugin` of package `floneum-cli v0.1.0 (C:\Users\xxx\.cargo\git\checkouts\floneum-61df347afec392d9\c314e5d\floneum-cli)`
>   versions that meet the requirements `*` are: 20.0.0
> 
>   the package `floneum_plugin` depends on `wasmtime-wasi`, with features: `preview2` but `wasmtime-wasi` does not have these features.
> 
>   failed to select a version for `wasmtime-wasi` which could resolve this conflict

**Steps To Reproduce**

Steps to reproduce the behavior. Include a code sample or a link to a repository with the code sample if applicable:

- `cargo install --git https://github.com/floneum/floneum floneum-cli`

**Expected behavior**

Installation shouldn't fail

**Environment:**

- Rust version: 1.76.0
- OS info: Windows 10

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
cargo install will create a new lock file for dependancies which doesn't play nicely with unpinned git dependancies. If you add the locked flag, installing the CLI succeeds on my device:

```sh
cargo install --git https://github.com/floneum/floneum floneum-cli --locked
```

https://github.com/floneum/floneum/pull/158 updates the version of wasmtime. I can pin the versions in that PR as well to fix this issue
