### ISSUE TITLE
Add support of Product scrapping 

### ISSUE THREAD

**Issue by red1** [floneum/floneum#164]
## Specific Demand

It would be great if the scraping could detect products and its data (Name, brand, price, currency, description and images)

## Implement Suggestion
Most of e-commerce sites are exposing these data on the product page in ld+json format using a structured data format. Looking into @type: Product would be a great naive first implementation

**Comment by ealmloff** [comment]
This isn't something I plan to support in the core Floneum plugins, but it would be a great addition as a community plugin!

For anyone interested in building a plugin to scrape e-commerce sites here are some resource that may be useful:
- [Plugin documentation](https://floneum.com/docs/developer/first_plugin)
- [The built in article scraping plugin](https://github.com/floneum/floneum/blob/main/floneum/plugins/get_article/src/lib.rs#L1-L23)
