### ISSUE TITLE
Run floneum on Arch linux fails with Error "GTK has not been initialized. Call `gtk::init` first"

### ISSUE THREAD

**Issue by phpwutz** [floneum/floneum#170]
**Problem**

Run on Arch linux fails with Error

**Steps To Reproduce**

- Checking out the 0.2.0 tag in git
- run `cargo build && cargo run`

Output:
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.32s
     Running `target/debug/floneum`
thread 'main' panicked at /home/xx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtk-0.16.2/src/auto/menu_item.rs:56:9:
GTK has not been initialized. Call `gtk::init` first.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Expected behavior**

I expect the floneum window to spawn

**Environment:**

```
$ rustup show
active toolchain
----------------
stable-x86_64-unknown-linux-gnu (default)
rustc 1.75.0 (82e1608df 2023-12-21)
```
- Renderer version: [`Kalosm main`]
- OS info: Arch Linux

**Questionnaire**

- [X] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
This looks like the same issue as https://github.com/floneum/floneum/issues/66 which was fixed in https://github.com/floneum/floneum/pull/161. You may just need to build a more recent version of Floneum
