### ISSUE TITLE
BUG: Wuerstchen is not working properly

### ISSUE THREAD

**Issue by newfla** [floneum/floneum#171]
**Problem**

Wuerstchen is not working properly showing different behaviour on different platform.
Tests have been made before #169 

**Steps To Reproduce**
[Source code](https://github.com/newfla/fourviere-podcast/blob/62b21bc478082820012a00f0be2f099d6e885d52/packages/app/src-tauri/src/commands/diffusion.rs#L147)
test command:  `cargo test --features=<metal|mkl|none> --package fourviere-podcast --bin fourviere-podcast -- commands::diffusion::test::simple_diffusion_test --exact --nocapture --ignored `

- When built without any feature, it seems like it is looping indefinitely. After 40 minutes it was still working. 

- Using mkl, crash with the following  `test commands::diffusion::test::simple_diffusion_test has been running for over 60 seconds
thread 'tokio-runtime-worker' panicked at /home/flavio/.cargo/git/checkouts/floneum-61df347afec392d9/fb5269d/models/rwuerstchen/src/lib.rs:639:22:
called `Result::unwrap()` on an `Err` value: MatMulUnexpectedStriding(MatMulUnexpectedStriding { lhs_l: Layout { shape: [1, 1, 1, 2304], stride: [2304, 1, 1, 1], start_offset: 0 }, rhs_l: Layout { shape: [1, 1, 2304, 5120], stride: [0, 0, 1, 2304], start_offset: 0 }, bmnk: (1, 1, 5120, 2304), msg: "non-contiguous lhs" })`

- Using metal, crash with the following `commands::diffusion::test::simple_diffusion_test' panicked at /Users/brainrepo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/candle-core-0.4.1/src/cpu_backend.rs:1194:21:
attempt to subtract with overflow`

**Expected behavior**

Working image generation

**Environment**

- mkl, no additional feature: wsl2, ryzen5 5600, 16Gb RAM
- metal: M2 PRO, 16Gb RAM

**Comment by ealmloff** [comment]
It looks like there are a few things going on here:
1) Accelerators were not supported by `Wuerstchen`, the `metal` and `cuda` features were no-ops. #173 adds support for `metal` (and hopefully `cuda`, but cuda support is untested) now that candle supports more quantized metal operations
2) Only some image sizes are supported by the `Wuerstchen` model: only resolutions that are a multiple of 128 are supported and resolutions outside of 1024x1024 and 1536x1536 may have poor generation quality. `Wuerstchen` trained on images with a resolution between 1024x1024 and 1536x1536.

If you want a lower quality images you can generate a higher quality image and then downscale the image to a smaller size

**Comment by ealmloff** [comment]
Looking through https://github.com/fourviere/fourviere-podcast/pull/239... It looks like you ran into a few rough edges:
- Proper error types for Whisper and Wuerstchen
- Implementing `Serialize` and `Deserialize` for common types like configs
- An async API with progress and time estimates for whisper and wuerstchen
- Display and FromStr for some enums like `WhisperLanguage` and `WhisperSource`
Anything else I am missing?

**Comment by newfla** [comment]
I did some tests and these are the results using mkl:
128x128: 9 minutes and image does not match the prompt
256x256: 25 minutes and image does not match the prompt

Unfortunately I'm on team red and can't try either cuda or metal.

If it's ok with you I can help with the other points you reported, starting from the estimate of the time for whisper which represents a priority for https://github.com/fourviere/fourviere-podcast/pull/239

**Comment by ealmloff** [comment]
> I did some tests and these are the results using mkl: 128x128: 9 minutes and image does not match the prompt 256x256: 25 minutes and image does not match the prompt
> 
> Unfortunately I'm on team red and can't try either cuda or metal.

I wouldn't expect image generation quality to be usable outside of the resolution range between 1024x1024 and 1536x1536

> If it's ok with you I can help with the other points you reported, starting from the estimate of the time for whisper which represents a priority for [fourviere/fourviere-podcast#239](https://github.com/fourviere/fourviere-podcast/pull/239)

That would be amazing!

**Comment by newfla** [comment]
@ealmloff is WuerstchenInferenceSettings::n_steps used? 🤔
I believe the parameter is only assigned and never used.

**Comment by ealmloff** [comment]
> @ealmloff is WuerstchenInferenceSettings::n_steps used? 🤔 I believe the parameter is only assigned and never used.

No, it isn't currently used. Looking at the [diffusers implementation](prior_num_inference_steps) Wuerstchen has two different step counts we can control: the prior time steps ([the 60 here](https://github.com/floneum/floneum/blob/5d5bda2e942feb9bed3883a46957c22d31bf8c99/models/rwuerstchen/src/lib.rs#L587)), and the decoder denoising steps ([the 12 here](https://github.com/floneum/floneum/blob/5d5bda2e942feb9bed3883a46957c22d31bf8c99/models/rwuerstchen/src/lib.rs#L628)). It probably doesn't make sense to just expose one "n_steps" setting

**Comment by newfla** [comment]
Ok I will try to include two different parameters along with introducing the asynchronous api for Wuerstchen =D

**Comment by newfla** [comment]
@ealmloff 
I am not 100% convinced of the current implementation of asyn api: in case I would like to stop the wuerstchen model I would have to wait for the generation of n samples to finish.
Similarly for whisper I would have to wait for the entire transcript to be generated.
Using a technique based on tokio::select! and tokio::cancellationToken I could stop whisper between the processing of the various rodio::Sample and wuerstchen between the samples generation

**Comment by ealmloff** [comment]
It looks like dropping the stream for the whisper model correctly stops the transcription. The segments whisper uses are larger, so you will need to use a larger audio file to see the effect (the jfk transcription is all in one segment).
