### ISSUE TITLE
zstd-safe compile error

### ISSUE THREAD

**Issue by DaveyUS** [floneum/floneum#204]
**Problem**

Trying to get the voice transcription example up and running and get this error:

```no `ZSTD_c_experimentalParam6` in `ZSTD_cParameter`
    |             help: a similar name exists in the module: `ZSTD_c_experimentalParam1`
    ```

Note that I am trying to implement this in my Tauri app, not sure if that's relevant.

**Steps To Reproduce**

- Follow quick start guide
- run npm run tauri dev
- error shows in console

**Expected behavior**

It builds properly.

**Environment:**

- Renderer version: Kalosm 0.2.1
- Rust version: 1.79.0
- OS info: Windows 11
- Tauri: 1.6.0

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by DaveyUS** [comment]
I also tried all other versions of Kalosm to no avail. I'd be really grateful for any help on this issue, really want to get it added to my app 🤘

**Comment by ealmloff** [comment]
You can add `zstd-sys = "=2.0.9"` to your cargo.toml to avoid the build error. One of the dependencies `kalosm` uses relied on unstable features that broke in a minor version. This issue should also be fixed in the git version of `kalosm`

**Comment by DaveyUS** [comment]
That fixed it thanks! Now I'm getting a different build error, starting a new issue

**Comment by DaveyUS** [comment]
Update: I fixed the other [build error](https://github.com/floneum/floneum/issues/206#issue-2370963356) by manually installing clang, but now I'm getting the zstd-safe compile error again, even with your fix implemented. I'm ultimately deeming this library isn't ready for my production app, but still figured I'd let you know. Thanks for the help!

**Comment by hanselke** [comment]
had the same initial error, which disappeared when i use zstd-sys = "=2.0.9". however i'm getting a new error 
```
error[E0133]: call to unsafe function `EnvOpenOptions::open` is unsafe and requires unsafe function or block
   --> /Users/hanselke/.cargo/registry/src/index.crates.io-6f17d22bba15001f/kalosm-language-0.2.2/src/vector_db.rs:98:19
    |
98  |           let env = EnvOpenOptions::new()
    |  ___________________^
99  | |             .map_size(TWENTY_HUNDRED_MIB)
100 | |             .open(path)?;
    | |_______________________^ call to unsafe function
    |
    = note: consult the function's documentation for information on how
```

**Comment by ealmloff** [comment]
Heed also published a minor release which makes a function unsafe in a minor version. `kalosm 0.2.2` and `kalosm-langauge 0.2.3` were both just published which fixes these issues
