### ISSUE TITLE
LLM is not managing memory properly

### ISSUE THREAD

**Issue by hanselke** [floneum/floneum#217]
**Problem**

Long conversations would eat up cuda GPU memory until it core dumbs
**Steps To Reproduce**
```
use kalosm::language::*;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let model = Llama::builder()
        .with_source(LlamaSource::mistral_7b_instruct_2())
        .build()
        .await?;
    let mut chat = Chat::builder(model)
        .with_system_prompt("The assistant will act like a pirate")
        .build();
    let prompt: &str = "hello how are you today";
    loop {
        let res = chat.add_message(prompt).await?;
        println!("Response: {:?}", res.all_text().await);
    }
    unreachable!("Infinite loop");
    Ok(())
}
```

**Expected behavior**

It should not core dump
**Environment:**

- Crate version: [`Kalosm main`]
- Rust version: [e.g. 1.78.0, `nightly`]
- OS info: Linux ubuntu]

**Questionnaire**

- [x ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
LLMs use attention which has quadratic memory complexity (`n` tokens takes `C*n^2`) memory. I'm splitting this into two different issues with more concrete things kalosm could do better here:
1) Use memory more efficiently: https://github.com/floneum/floneum/issues/219
2) Expose information about memory usage of each model: https://github.com/floneum/floneum/issues/220
