### ISSUE TITLE
How to pass raw chunks?

### ISSUE THREAD

**Issue by usametov** [floneum/floneum#261]
I have my chunks processed by my other tool, so now I just want to add them "as is" to document_table. 
This sounds very trivial, but what is the best way to do that?

**Comment by ealmloff** [comment]
You can use [insert_with_chunks](https://docs.rs/kalosm/0.3.2/kalosm/language/struct.DocumentTable.html#method.insert_with_chunks) to insert a value with pre-computed chunks into the table. If you have the chunk ranges without the embeddings, you can calculate the embeddings with [embed_batch](https://docs.rs/kalosm/0.3.2/kalosm/language/trait.Embedder.html#example) with the same embedding you used in the table

**Comment by usametov** [comment]
cool, thanks a lot :)
