### ISSUE TITLE
kalosm-sound 0.3.4 not compiling: `Clone` missing for `Device`

### ISSUE THREAD

**Issue by gpoblon** [floneum/floneum#262]
**Problem**

kalosm-sound not compiling: `Clone` missing for `Device`

**Steps To Reproduce**

New crate with kalosm 0.3.2, "sound" feature.
Tried to compile the transcribe example, got this error from `kalosm-sound-0.3.4\src\source\mic.rs:67:48`

**Environment:**

- Crate version: 0.3.2 (also tried 0.3.0)
- Rust version: 1.80.1
- OS info: Windows 11 (side note: could be nice to indicate clang as requirement for windows in the documentation/readme, which is painful to install on windows)

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
I'm guessing you are pulling in a older version of `cpal` somewhere in your dependencies I think https://github.com/floneum/floneum/pull/263 will fix this issue, but it would be great if you could confirm. Newer versions of cpal implement Clone for Device, but older versions do not

**Comment by gpoblon** [comment]
Hi Evan,

Thank you for the fix. I'm not sure whether it could be related to my deps, at least I have no other deps but tokio and kalosm.
`kalosm = { git = "https://github.com/floneum/floneum", branch = "main", features="sound" }`
You merged it so I directly tried on main and got this conflict with cpal:
![image](https://github.com/user-attachments/assets/cfd69b9a-f71c-4fa9-88ae-1771b7c881bb)

**Comment by ealmloff** [comment]
Hmm, I can't reproduce that issue with kalosm and tokio added as dependencies. [Here](https://github.com/ealmloff/kalosm-262) is my attempt. Could you try to create a reproduction in a public repo?

**Comment by gpoblon** [comment]
My bad, a `Cargo.lock` removal did the tick, issue's gone.
