### ISSUE TITLE
"Unsupported cuda toolkit version: `12.6`. Please raise a github issue."

### ISSUE THREAD

**Issue by tyressk** [floneum/floneum#277]
**Problem**
Building with CUDA gives "Unsupported cuda toolkit version".

**Steps To Reproduce**

- Cuda version:

```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Wed_Aug_14_10:10:22_PDT_2024
Cuda compilation tools, release 12.6, V12.6.68
Build cuda_12.6.r12.6/compiler.34714021_0
```
- kalosm Cargo.toml line:
`kalosm = { git = "https://github.com/floneum/floneum", version = "0.3.2", features = ["language","cuda"] }`

- Build error from `cargo build --release`:

```
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/home/tyress/ai-words/target/release/build/cudarc-2fad8b87528ebdbf/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-env-changed=CUDA_ROOT
  cargo:rerun-if-env-changed=CUDA_PATH
  cargo:rerun-if-env-changed=CUDA_TOOLKIT_ROOT_DIR

  --- stderr
  thread 'main' panicked at /home/tyress/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cudarc-0.11.9/build.rs:82:14:
  Unsupported cuda toolkit version: `12.6`. Please raise a github issue.
  stack backtrace:
     0: rust_begin_unwind
     1: core::panicking::panic_fmt
     2: build_script_build::cuda_version_from_build_system
     3: build_script_build::main
     4: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Environment:**

- Crate version: 0.3.2
- Rust version:  1.81.0 
- OS info: Linux

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by lukas0008** [comment]
This seems to be a problem with one of the dependencies - `cudarc`, one of the sub-dependencies depends on version `0.11.9`, while cuda 12.6 is supported only as of `0.12.1` - https://github.com/coreylowman/cudarc/pull/286

When searching through my Cargo.lock file, I can see that `candle-core` requires it.

**Comment by tyressk** [comment]
It works for me after doing an indiscriminate `cargo update` on floneum @lukas0008

**Comment by ealmloff** [comment]
This should be fixed by https://github.com/floneum/floneum/pull/278
