### ISSUE TITLE
Models are downloaded, but generation time is infinite

### ISSUE THREAD

**Issue by InAnYan** [floneum/floneum#296]
**Problem**

I played with kalosm and made a simple CLI app with chat and structured generation.

Models are successfully downloaded, however, chat message generation and structured generation takes infinite time.

I already used local llms and other crates/(libraries from other programming languages), ollama, etc. Everything worked fine there, so my computer can handle LLMs.

Specifically, I used Llama 1.1b (if I remember correctly), and TinyLLama chat.

**Steps To Reproduce**

1. Just make a simple app that uses chat and `add_message` or task with structured generation and `run()`

**Expected behavior**

LLM output. Slow/fast - doesn't matter, but some output.

**Environment:**

- Crate version: here is an excerpt from my Cargo.toml:

```toml
kalosm = "0.3.2"
kalosm-language = "0.3.3"
kalosm-llama = "0.3.4"
kalosm-sample = "0.3.2"
```

And I'm running LLMs on CPU.

- Rust version: 1.82
- OS info: Linux Mint 22

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by InAnYan** [comment]
![Image](https://github.com/user-attachments/assets/8c0b1c17-30b9-4880-854d-19b739dffb6d)

Well, something's working...

**Comment by InAnYan** [comment]
And here is the chat code. I didn't include it in the issue body, because, I think, it's trivial, I doubt there is any mistake:

```rust
    let mut chat = Chat::builder(llm)
        .with_system_prompt("You are a helpful asistant.")
        .build();

    loop {
        let input: String = Input::new()
            .with_prompt("User")
            .interact_text()
            .context("unable to get input from console")?;

        if input == "/q" {
            break;
        }

        let response = chat.add_message(input).all_text().await;

        println!("Assistant: {}", response);
    }
```

**Comment by ealmloff** [comment]
First, make sure you run in release mode with `cargo run --release`. Models will run extremely slow on the CPU without optimizations turned on.

If that doesn't fix the issue, try streaming the text instead of waiting for the whole response. LLMs can get stuck in a loop repeating the same text instead of ending the message which might make it look like text isn't generating:

```rust
use kalosm::language::*;

#[tokio::main]
async fn main() -> Result<(), anyhow::Error> {
    let llm = Llama::builder().with_source(LlamaSource::llama_3_2_1b_chat()).build().await?;
    let mut chat = Chat::builder(llm)
    .with_system_prompt("You are a helpful asistant.")
    .build();

    loop {
        let input = prompt_input("User: ")?;

        if input == "/q" {
            break;
        }

        print!("Assistant: ");
        // to_std_out streams the output to the console instead of waiting for the whole thing
        chat.add_message(input).to_std_out().await?;
        println!();
    }

    Ok(())
}
```
