### ISSUE TITLE
Add vulkan support

### ISSUE THREAD

**Issue by dbkblk** [floneum/floneum#297]
## Specific Demand

whisper.cpp and the bindings of whisper-rs added vulkan support. Could you add it to rwhisper ?

Thank you for your work so far :)

**Comment by ealmloff** [comment]
Kalosm uses [candle](https://github.com/huggingface/candle) for lower level ML operations. It is limited by the accelerators candle supports. If you have an AMD gpu, there is an issue about AMD support in candle [here](https://github.com/huggingface/candle/issues/346)

**Comment by dbkblk** [comment]
Thank you for your answer!
