### ISSUE TITLE
Failed to compile `kalosm-sound` when using `kalosm` with `features = [ "full" ]`

### ISSUE THREAD

**Issue by iganev** [floneum/floneum#302]
**Problem**

Following the cargo crate readme guide and including `kalosm` in an empty project with `features = [ "full" ]` consistently produces the following compilation error:

```
error[E0599]: no method named `clone` found for struct `Device` in the current scope
  --> /home/ivan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/kalosm-sound-0.3.4/src/source/mic.rs:67:48
   |
67 |         let device: cpal::Device = self.device.clone();
   |                                                ^^^^^ method not found in `Device`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `kalosm-sound` (lib) due to 1 previous error
```

Perhaps a missing derive? But its probably not that simple...

**Steps To Reproduce**

- create project
- include tokio and kalosm as described by the cargo crate readme example
- try to `cargo build`

**Expected behavior**

Build success.

**Environment:**

- Crate version: kalosm 0.3.2
- Rust version: 1.81.0
- OS info: openSUSE Tumbleweed; Linux 6.11.5-1-default

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by ealmloff** [comment]
That error looks similar to https://github.com/floneum/floneum/issues/262. You can try updating cpal with `cpal = "0.15.3"` and `cargo update` or update to the git version of kalosm

**Comment by iganev** [comment]
Awesome! Thanks for the hint! Brilliant work btw!
