### ISSUE TITLE
Usage of RAG term in the documentation

### ISSUE THREAD

**Issue by InAnYan** [floneum/floneum#306]
Hello!

I've seen in https://docs.rs/kalosm/0.3.2/kalosm/ that you use term RAG and it expands in "resource-augmented generation".

Though, I've never seen a term like that, it's always been "**Retrieval**-Augmented Generation". I couldn't find any article on arxiv with "Resource" instead of "Retrieval".

Though, I haven't spent much time in analyzing this linguistic moment, and I'm not an expert here, but:

- Wouldn't it be better to use terms that already used widely?
- Or maybe there is a reason why it's called "resource"?

**Comment by ealmloff** [comment]
Fixed by a89b03c
