### ISSUE TITLE
Integrate cloud/remote models

### ISSUE THREAD

**Issue by ealmloff** [floneum/floneum#67]
Create an integration for remote models like Chat GPT and remote versions of Llama models

**Comment by ealmloff** [comment]
> Hi @ealmloff I believe we can help with this issue. I’m the maintainer of LiteLLM https://github.com/BerriAI/litellm
> 
> **TLDR:** **We allow you to use any LLM as a drop in replacement for `gpt-3.5-turbo`- You can use llama/gpt/claude (100+ LLMs)**
> 
> If you don't have access to certain LLMs you can use our proxy server or spin up your own proxy server using LiteLLM
> 
> ## Usage
> This calls the provider API directly
> 
> ```python
> from litellm import completion
> import os
> ## set ENV variables 
> os.environ["OPENAI_API_KEY"] = "your-key" # 
> messages = [{ "content": "Hello, how are you?","role": "user"}]
> 
> # openai call
> response = completion(model="gpt-3.5-turbo", messages=messages)
> 
> # falcon call
> response = completion(model="falcon-40b", messages=messages)
> ```

That looks like exactly what we need, but Floneum is written entirely run rust. We could potentially run litellm in a rust interpreter of python, but I think writing a simple wrapper for GPT compatible servers or using an existing rust open ai library may be easier.

I am planning on implementing this in https://github.com/floneum/floneum/pull/69

**Comment by ishaan-jaff** [comment]
no worries - are you planning on creating a server to make your LLM API Calls ? If so we can help you spin one up / maintain it ? 

That way it's language agnostic

**Comment by ealmloff** [comment]
> no worries - are you planning on creating a server to make your LLM API Calls ? If so we can help you spin one up / maintain it ?
> 
> That way it's language agnostic

In the future, I would love to host a version of Floneum on the cloud to get faster inference, but for now I plan on just supporting any user supplied API like chat GPT or a self hosted server.

If you have any tutorials that help people create a chat GPT compatible server, I would love to link to them once I get remote models working in Floneum. (Especially if the resources are accessible from a non-technical background)

**Comment by krrishdholakia** [comment]
Hey @ealmloff  we do! https://github.com/BerriAI/liteLLM-proxy

**Comment by krrishdholakia** [comment]
@ealmloff update on this - it's now a 1 line of code: 
```
litellm --model <your-model-name>
```

https://docs.litellm.ai/docs/proxy_server

**Comment by krrishdholakia** [comment]
@ealmloff did this solve your problem?

**Comment by ealmloff** [comment]
> @ealmloff did this solve your problem?

`litellm` will probably work to host models, but Floneum doesn't have cloud model support yet
